# Generated by Django 6.0.7 on 2026-07-18 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('gemstone_type', models.CharField(blank=True, choices=[('Alexandrite', 'Alexandrite'), ('Amber', 'Amber'), ('Cats Eye', 'Cats Eye'), ('Malachite', 'Malachite'), ('Morganite', 'Morganite'), ('Aquamarine', 'Aquamarine'), ('Diamond', 'Diamond'), ('Emerald', 'Emerald'), ('Fluorite Green', 'Fluorite Green'), ('Fluorite Purple', 'Fluorite Purple'), ('Garnet', 'Garnet'), ('Peridot', 'Peridot'), ('Ruby', 'Ruby'), ('Sapphire Blue', 'Sapphire Blue'), ('Sapphire Pink', 'Sapphire Pink'), ('Topaz Blue', 'Topaz Blue'), ('Topaz Yellow', 'Topaz Yellow'), ('Tourmaline Black', 'Tourmaline Black'), ('Turquoise', 'Turquoise'), ('Zircon', 'Zircon')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('color', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('treatment', models.CharField(blank=True, max_length=100)),
                ('certification', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('Rough', 'Rough'), ('Cut', 'Cut'), ('Polished', 'Polished'), ('Faceted', 'Faceted'), ('Cabochon', 'Cabochon')], max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold')], default='Available', max_length=20)),
                ('ai_prediction', models.CharField(blank=True, max_length=100)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_ai_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/listings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.listing')),
            ],
        ),
    ]
