# Generated by Django 6.0.7 on 2026-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='resend_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
